const copy = {
  de: { language: 'Sprache', close: 'Schließen', more: 'Weitere Informationen →', noDescription: 'Keine Beschreibung vorhanden.', programme: 'Zoo-Programm', events: 'Veranstaltungen', showOnMap: 'Auf der Karte zeigen', noEvents: 'Keine Veranstaltungen', noEventsText: 'Zurzeit sind keine Termine für Besucher veröffentlicht.', nextEvent: 'Nächster Termin', clock: 'Uhr', searchLabel: 'Karte durchsuchen', searchPlaceholder: 'Tier oder Ort suchen …', clearSearch: 'Suche löschen', searchResults: 'Suchergebnisse', noSearchResults: 'Keine passenden Orte gefunden.', categories: 'Kategorien', myLocation: 'Mein Standort' },
  en: { language: 'Language', close: 'Close', more: 'More information →', noDescription: 'No description available.', programme: 'Zoo programme', events: 'Events', showOnMap: 'Show on map', noEvents: 'No events', noEventsText: 'There are currently no published events.', nextEvent: 'Next event', clock: '', searchLabel: 'Search the map', searchPlaceholder: 'Search for an animal or place …', clearSearch: 'Clear search', searchResults: 'Search results', noSearchResults: 'No matching places found.', categories: 'Categories', myLocation: 'My location' },
  nl: { language: 'Taal', close: 'Sluiten', more: 'Meer informatie →', noDescription: 'Geen beschrijving beschikbaar.', programme: 'Zooprogramma', events: 'Evenementen', showOnMap: 'Op de kaart tonen', noEvents: 'Geen evenementen', noEventsText: 'Er zijn momenteel geen gepubliceerde evenementen.', nextEvent: 'Volgende evenement', clock: 'uur', searchLabel: 'Kaart doorzoeken', searchPlaceholder: 'Zoek een dier of plaats …', clearSearch: 'Zoekopdracht wissen', searchResults: 'Zoekresultaten', noSearchResults: 'Geen passende plaatsen gevonden.', categories: 'Categorieën', myLocation: 'Mijn locatie' },
  pl: { language: 'Język', close: 'Zamknij', more: 'Więcej informacji →', noDescription: 'Brak opisu.', programme: 'Program zoo', events: 'Wydarzenia', showOnMap: 'Pokaż na mapie', noEvents: 'Brak wydarzeń', noEventsText: 'Obecnie nie ma opublikowanych wydarzeń.', nextEvent: 'Najbliższe wydarzenie', clock: '', searchLabel: 'Przeszukaj mapę', searchPlaceholder: 'Szukaj zwierzęcia lub miejsca …', clearSearch: 'Wyczyść wyszukiwanie', searchResults: 'Wyniki wyszukiwania', noSearchResults: 'Nie znaleziono pasujących miejsc.', categories: 'Kategorie', myLocation: 'Moja lokalizacja' },
  fr: { language: 'Langue', close: 'Fermer', more: 'Plus d’informations →', noDescription: 'Aucune description disponible.', programme: 'Programme du zoo', events: 'Événements', showOnMap: 'Afficher sur la carte', noEvents: 'Aucun événement', noEventsText: 'Aucun événement n’est actuellement publié.', nextEvent: 'Prochain événement', clock: '', searchLabel: 'Rechercher sur la carte', searchPlaceholder: 'Rechercher un animal ou un lieu …', clearSearch: 'Effacer la recherche', searchResults: 'Résultats de recherche', noSearchResults: 'Aucun lieu correspondant trouvé.', categories: 'Catégories', myLocation: 'Ma position' },
  es: { language: 'Idioma', close: 'Cerrar', more: 'Más información →', noDescription: 'No hay descripción disponible.', programme: 'Programa del zoo', events: 'Eventos', showOnMap: 'Mostrar en el mapa', noEvents: 'No hay eventos', noEventsText: 'Actualmente no hay eventos publicados.', nextEvent: 'Próximo evento', clock: '', searchLabel: 'Buscar en el mapa', searchPlaceholder: 'Buscar un animal o lugar …', clearSearch: 'Borrar búsqueda', searchResults: 'Resultados de búsqueda', noSearchResults: 'No se encontraron lugares coincidentes.', categories: 'Categorías', myLocation: 'Mi ubicación' },
  it: { language: 'Lingua', close: 'Chiudi', more: 'Maggiori informazioni →', noDescription: 'Nessuna descrizione disponibile.', programme: 'Programma dello zoo', events: 'Eventi', showOnMap: 'Mostra sulla mappa', noEvents: 'Nessun evento', noEventsText: 'Al momento non ci sono eventi pubblicati.', nextEvent: 'Prossimo evento', clock: '', searchLabel: 'Cerca sulla mappa', searchPlaceholder: 'Cerca un animale o un luogo …', clearSearch: 'Cancella ricerca', searchResults: 'Risultati di ricerca', noSearchResults: 'Nessun luogo corrispondente trovato.', categories: 'Categorie', myLocation: 'La mia posizione' },
  da: { language: 'Sprog', close: 'Luk', more: 'Flere oplysninger →', noDescription: 'Ingen beskrivelse tilgængelig.', programme: 'Zoo-program', events: 'Arrangementer', showOnMap: 'Vis på kortet', noEvents: 'Ingen arrangementer', noEventsText: 'Der er ingen offentliggjorte arrangementer i øjeblikket.', nextEvent: 'Næste arrangement', clock: '', searchLabel: 'Søg på kortet', searchPlaceholder: 'Søg efter et dyr eller sted …', clearSearch: 'Ryd søgning', searchResults: 'Søgeresultater', noSearchResults: 'Ingen matchende steder fundet.', categories: 'Kategorier', myLocation: 'Min placering' },
} as const

export type VisitorCopy = { [K in keyof typeof copy.de]: string }
export function visitorCopy(locale: string): VisitorCopy { return copy[locale as keyof typeof copy] ?? copy.de }
